LPS-156315 Add defaultValue in BusinessType
liferay-zulu/liferay-portal pull request #219
Opened 2022-06-17 20:27 UTC by seltong

2022-06-17 20:27 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-06-20 22:11 UTC, naraandrade commented
Just started reviewing :)

2022-06-21 16:43 UTC, naraandrade commented
Just started reviewing :)

2022-06-21 21:00 UTC, MarinhoFeliphe requested changes
Very nice @seltong!

2022-06-21 21:00 UTC, MarinhoFeliphe commented on modules/apps/object/object-api/src/main/resources/com/liferay/object/service/packageinfo
> +version 20.0.0
Hi @seltong,

Move this change to the proper commit,

Thank you!

2022-06-21 21:00 UTC, MarinhoFeliphe commented on modules/apps/object/object-admin-rest-api/src/main/resources/com/liferay/object/admin/rest/dto/v1_0/util/packageinfo
> +version 2.1.0
Hi @seltong,

Move this change to the semver commit.

Thanks!

2022-06-22 13:37 UTC, naraandrade commented
Just started reviewing :)

2022-06-22 18:14 UTC, naraandrade commented
Just started reviewing :)

2022-06-22 18:38 UTC, naraandrade commented
Just started reviewing :)

2022-06-22 19:01 UTC, naraandrade commented
Resent here: #224

2022-06-22 19:01 UTC, closed without merging