LPS-158088 Fix incorrect content sent to validations sidebar
liferay-zulu/liferay-portal pull request #266
Opened 2022-07-12 16:08 UTC by seltong

2022-07-12 18:38 UTC, seltong commented
ci:test:sf

2022-07-12 18:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/3512/">test-portal-source-format#3512</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/3512/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-zulu/liferay-portal/pull/266">liferay-zulu#266</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1904249797">[master] ci:test:sf - seltong &gt; liferay-zulu - PR#266 - 2022-07-12[11:39:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/13025/">publish-testray-report#13025</a><br/></div></div>

2022-07-12 20:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-21.liferay.com/job/test-portal-source-format/6430/">test-portal-source-format#6430</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-21.liferay.com/userContent/jobs/test-portal-source-format/builds/6430/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-zulu/liferay-portal/pull/266">liferay-zulu#266</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1904461005">[master] ci:test:sf - seltong &gt; liferay-zulu - PR#266 - 2022-07-12[13:31:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-21.liferay.com/job/publish-testray-report/2297/">publish-testray-report#2297</a><br/></div></div>

2022-07-12 21:01 UTC, seltong commented
ci:test:sf

2022-07-12 21:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2586/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2586/jenkins-report.html">here</a>.</b></p>

2022-07-12 21:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f6a6470458cb2ed43bc60e278021a9ff9c0f3dfd">f6a6470458cb2ed43bc60e278021a9ff9c0f3dfd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/seltong/liferay-portal/tree/LPS-158088">LPS-158088</a><br/>Branch GIT ID: <a href="https://github.com/seltong/liferay-portal/commit/808cf4d6811f7d93332432677cfa043ef38c1428">808cf4d6811f7d93332432677cfa043ef38c1428</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2586/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2586/jenkins-report.html">here</a>.</h5></details></html>

2022-07-12 21:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2586/">test-portal-source-format#2586</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2586/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-zulu/liferay-portal/pull/266">liferay-zulu#266</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1904466910">[master] ci:test:sf - seltong &gt; liferay-zulu - PR#266 - 2022-07-12[14:01:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9447/">publish-testray-report#9447</a><br/></div></div>

2022-07-13 11:49 UTC, seltong commented
ci:test:sf

2022-07-13 11:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/2700/">test-portal-source-format#2700</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/2700/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-zulu/liferay-portal/pull/266">liferay-zulu#266</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1905049925">[master] ci:test:sf - seltong &gt; liferay-zulu - PR#266 - 2022-07-13[04:49:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/9807/">publish-testray-report#9807</a><br/></div></div>

2022-07-18 16:37 UTC, MarinhoFeliphe commented on modules/apps/object/object-service/src/main/java/com/liferay/object/service/impl/ObjectValidationRuleLocalServiceImpl.java
> +		throws PortalException {
Hi @seltong,

try to merge this method with the other one for ObjectEntry by using  `instanceof`.

Thanks!

2022-07-18 16:40 UTC, MarinhoFeliphe commented on modules/apps/object/object-web/src/main/java/com/liferay/object/web/internal/object/definitions/display/context/util/ObjectCodeEditorUtil.java
> +							objectField.getDBColumnName(), StringPool.UNDERLINE)
Hi @seltong,

Slack me tomorrow to talk about this approach, I believe we can try to keep the objectFieldName for Custom Objects and get the DBColumnName for System ones.

Thanks!

2022-07-18 16:52 UTC, MarinhoFeliphe commented on modules/apps/object/object-web/src/main/java/com/liferay/object/web/internal/object/definitions/frontend/taglib/servlet/taglib/ObjectDefinitionsValidationsScreeNavigationCategory.java
> +
Hi @seltong,

I believe we can invert this conditionals, I mean something like this:

````
if (!objectDefinition.isDefaultStorageType()) {
  return false;
}

if (!objectDefinition.isSystem()) {
   return true;
}

return GetterUtil.getBoolean(PropsUtil.get("feature.flag.LPS-151671");
````

2022-07-18 22:14 UTC, seltong commented
ci:test:sf

2022-07-18 22:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/2847/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/2847/jenkins-report.html">here</a>.</b></p>

2022-07-18 22:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/2847/">test-portal-source-format#2847</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/2847/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-zulu/liferay-portal/pull/266">liferay-zulu#266</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1910415542">[master] ci:test:sf - seltong &gt; liferay-zulu - PR#266 - 2022-07-18[15:15:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/10400/">publish-testray-report#10400</a><br/></div></div>

2022-07-18 22:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/2853/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2853/jenkins-report.html">here</a>.</b></p>

2022-07-18 22:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9a335bd878bf323b695ad5deab0ded3bed7c34d6">9a335bd878bf323b695ad5deab0ded3bed7c34d6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/seltong/liferay-portal/tree/LPS-158088">LPS-158088</a><br/>Branch GIT ID: <a href="https://github.com/seltong/liferay-portal/commit/a7efe3a00e99d9cc533c7218a5fbd04925b7f9a9">a7efe3a00e99d9cc533c7218a5fbd04925b7f9a9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/2853/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2853/jenkins-report.html">here</a>.</h5></details></html>

2022-07-18 22:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/2853/">test-portal-source-format#2853</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2853/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-zulu/liferay-portal/pull/266">liferay-zulu#266</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1910415687">[master] ci:test:sf - seltong &gt; liferay-zulu - PR#266 - 2022-07-18[15:24:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/10581/">publish-testray-report#10581</a><br/></div></div>

2022-07-19 16:06 UTC, MarinhoFeliphe requested changes

2022-07-19 16:18 UTC, seltong commented
ci:test:sf

2022-07-19 16:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/1645/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/1645/jenkins-report.html">here</a>.</b></p>

2022-07-19 16:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/3fcd86ff0768843e20cb12deb570377e8a6b49e1">3fcd86ff0768843e20cb12deb570377e8a6b49e1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/seltong/liferay-portal/tree/LPS-158088">LPS-158088</a><br/>Branch GIT ID: <a href="https://github.com/seltong/liferay-portal/commit/b83bfdcec65b1e66f781dd01b5510e84c3c2d1c1">b83bfdcec65b1e66f781dd01b5510e84c3c2d1c1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/1645/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/1645/jenkins-report.html">here</a>.</h5></details></html>

2022-07-25 15:39 UTC, closed without merging