Lps-157721: Change Notification link to use always use '/manage' as layout friendlyURL
liferay-zulu/liferay-portal pull request #285
Opened 2022-07-19 04:31 UTC by kristofloneck

If comments needs to removed/added, just tell me and removed/add them from the code

2022-07-19 04:32 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-07-19 07:20 UTC, kristofloneck commented
ci:test

2022-07-19 07:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>default</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3533/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3533/jenkins-report.html">here</a>.</b></p>

2022-07-19 13:03 UTC, MarinhoFeliphe commented
ci:test:relevant

2022-07-19 13:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3541/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3541/jenkins-report.html">here</a>.</b></p>

2022-07-19 13:07 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e417ae9110d3817980bdb9dfd0a9b9825326e32b">e417ae9110d3817980bdb9dfd0a9b9825326e32b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/kristofloneck/liferay-portal/tree/LPS-157721_master">LPS-157721_master</a><br/>Branch GIT ID: <a href="https://github.com/kristofloneck/liferay-portal/commit/cacbbe560b3c2d143f5933c34346f7d95e588554">cacbbe560b3c2d143f5933c34346f7d95e588554</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/2937/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/2937/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 13 formatting issues:
     [java] 1: '\{' is not preceded with whitespace., see https://checkstyle.sourceforge.io/config_whitespace.html#WhitespaceAround: ./portal-impl/src/com/liferay/portlet/internal/NotificationRenderURLImpl.java 27 (Checkstyle:WhitespaceAroundCheck)
     [java] 2: 'if' is not followed by whitespace., see https://checkstyle.sourceforge.io/config_whitespace.html#WhitespaceAround: ./portal-impl/src/com/liferay/portlet/internal/NotificationRenderURLImpl.java 49 (Checkstyle:WhitespaceAroundCheck)
     [java] 3: Use braces around if-statement clause: ./portal-impl/src/com/liferay/portlet/internal/NotificationRenderURLImpl.java 49 (Checkstyle:SingleStatementClauseCheck)
     [java] 4: Rename variable 'isItFromNotification' to 'itFromNotification': ./portal-impl/src/com/liferay/portlet/internal/PortletURLFactoryImpl.java 215 (Checkstyle:VariableNameCheck)
     [java] 5: Rename variable 'isItNotificaitonPortlet' to 'itNotificaitonPortlet': ./portal-impl/src/com/liferay/portlet/internal/PortletURLFactoryImpl.java 254 (Checkstyle:VariableNameCheck)
     [java] 6: 'if' is not followed by whitespace., see https://checkstyle.sourceforge.io/config_whitespace.html#WhitespaceAround: ./portal-impl/src/com/liferay/portlet/internal/PortletURLFactoryImpl.java 256 (Checkstyle:WhitespaceAroundCheck)
     [java] 7: '\{' is not preceded with whitespace., see https://checkstyle.sourceforge.io/config_whitespace.html#WhitespaceAround: ./portal-impl/src/com/liferay/portlet/internal/PortletURLImpl.java 945 (Checkstyle:WhitespaceAroundCheck)
     [java] 8: Rename variable 'isItFromNotification' to 'itFromNotification': ./portal-kernel/src/com/liferay/portal/kernel/portlet/PortletURLFactory.java 87 (Checkstyle:VariableNameCheck)
     [java] 9: Rename variable 'isItNotification' to 'itNotification': ./portal-kernel/src/com/liferay/portal/kernel/portlet/PortletURLFactoryUtil.java 81 (Checkstyle:VariableNameCheck)
     [java] 10: ./portal-impl/src/com/liferay/portlet/internal/NotificationRenderURLImpl.java expected:&lt;...let.PortletRequest;
     [java] [
     [java] import javax.servlet.http.HttpServletRequest;
     [java] 
     [java] /**
     [java]  * @author Krist??f Loneck
     [java]  */
     [java] public class NotificationRenderURLImpl extends RenderURLImpl \{
     [java] 
     [java]   public NotificationRenderURLImpl(
     [java]     HttpServletRequest httpServletRequest, Portlet portlet, Layout layout,</pre></details></html>

2022-07-19 13:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/2937/">test-portal-source-format#2937</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/2937/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-zulu/liferay-portal/pull/285">liferay-zulu#285</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1911262416">[master] ci:test:sf - kristofloneck &gt; liferay-zulu - PR#285 - 2022-07-19[06:03:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/10461/">publish-testray-report#10461</a><br/></div></div>

2022-07-19 16:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 26 out of 26 jobs passed</h3><h3>:x: ci:test:relevant - 865 out of 890 jobs passed in 3 hours 26 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3571">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1377401_3541</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e417ae9110d3817980bdb9dfd0a9b9825326e32b">e417ae9110d3817980bdb9dfd0a9b9825326e32b</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e09a23834186cfe4dc82e8d7de21702e146d98de">e09a23834186cfe4dc82e8d7de21702e146d98de</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3570">Acceptance Upstream DXP (master) #3570</a></p><details><summary><strong>ci:test:stable - 26 out of 26 jobs PASSED</strong></summary><details><summary><strong>26 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122995/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/110617/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126273/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126283/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/118747/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/112088/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/47503/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/127356/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/55997/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/56517/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126287/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126340/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126342/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53745/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/109464/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/128455/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122381/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/128514/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/109512/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/68610/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/55458/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/50186/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126384/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/56543/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/51685/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/110607/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 865 out of 890 jobs PASSED</strong></summary><div><h4>25 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3541/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53799/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/109576/"><strike>functional-tomcat90-mysql57-jdk8/2/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/127412/"><strike>functional-tomcat90-mysql57-jdk8/2/1</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/127408/"><strike>functional-tomcat90-mysql57-jdk8/2/2</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126328/"><strike>functional-tomcat90-mysql57-jdk8/2/3</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/109580/"><strike>functional-tomcat90-mysql57-jdk8/2/4</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/123081/"><strike>functional-tomcat90-mysql57-jdk8/2/5</strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/56282/"><strike>functional-tomcat90-mysql57-jdk8/3/5</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/109539/"><strike>functional-tomcat90-mysql57-jdk8/4/14</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/105535/"><strike>functional-tomcat90-mysql57-jdk8/6/4</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/126368/"><strike>functional-tomcat90-mysql57-jdk8/8/13</strike></a></li><li> [...]

2022-07-19 16:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3541/">test-portal-acceptance-pullrequest(master)#3541</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3541/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-zulu/liferay-portal/pull/285">liferay-zulu#285</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1911455065">[master] ci:test:relevant - kristofloneck &gt; liferay-zulu - PR#285 - 2022-07-19[06:04:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/8426/">publish-testray-report#8426</a><br/></div></div>

2022-07-19 19:11 UTC, seltong commented
Hi @kristofloneck , could you please check the SF faults?

2022-07-20 11:18 UTC, seltong commented
ci:test:sf

2022-07-20 11:21 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2b6af22d5ab7595d8eb09194c29fcabdbe743459">2b6af22d5ab7595d8eb09194c29fcabdbe743459</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/kristofloneck/liferay-portal/tree/LPS-157721_master">LPS-157721_master</a><br/>Branch GIT ID: <a href="https://github.com/kristofloneck/liferay-portal/commit/a8718a883f33bfc1ab2911fc9c69948cb343dae0">a8718a883f33bfc1ab2911fc9c69948cb343dae0</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1751/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1751/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./portal-impl/src/com/liferay/portlet/internal/NotificationRenderURLImpl.java expected:&lt;...URL("/manage");
     [java]     \}
     [java] [
     [java] ]    return super.gener...&gt; but was:&lt;...URL("/manage");
     [java]     \}
     [java] []    return super.gener...&gt;
     [java] 2: ./portal-impl/src/com/liferay/portlet/internal/PortletURLFactoryImpl.java expected:&lt;...eResponse.Copy copy,[ boolean fromNotification) \{
     [java] 
     [java]     if (PortletRequest.RENDER_PHASE.equals(lifecycle) &amp;&amp; ]fromNotification)
     [java] 
     [java]   ...&gt; but was:&lt;...eResponse.Copy copy,[
     [java]     boolean fromNotification) \{
     [java] 
     [java]     if (PortletRequest.RENDER_PHASE.equals(lifecycle) &amp;&amp;
     [java]       ]fromNotification)
     [java] 
     [java]   ...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:442)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:284)
[stopwatch] [run.batch.test.action: 1:01.554 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:450: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:593: Java returned: 1
      [get] Getting: http://test-1-38/job/test-portal-source-format/1751//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20220720042112233.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20220720042112233.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null811552449.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null567571881
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 184ms</pre></details></html>

2022-07-20 11:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/1751/">test-portal-source-format#1751</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/1751/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-zulu/liferay-portal/pull/285">liferay-zulu#285</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1912101097">[master] ci:test:sf - kristofloneck &gt; liferay-zulu - PR#285 - 2022-07-20[04:18:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/5577/">publish-testray-report#5577</a><br/></div></div>

2022-07-21 17:45 UTC, seltong requested changes

2022-07-21 17:45 UTC, seltong commented on portal-impl/src/com/liferay/portlet/internal/PortletURLFactoryImpl.java
> +		String lifecycle, boolean isItFromNotification) {
Hi @kristofloneck could you please rename `isItFromNotification` parameter to `notification`?

2022-07-21 17:45 UTC, seltong commented on portal-impl/src/com/liferay/portlet/internal/PortletURLFactoryImpl.java
> +		String lifecycle, MimeResponse.Copy copy, boolean isItNotificaitonPortlet) {
Hi @kristofloneck could you please rename `isItNotificaitonPortlet` parameter to `notification`?

2022-07-21 17:56 UTC, seltong commented
Hi @kristofloneck sorry for delay
Could you check if it's possible fix this bug changing the `serviceContext` passed as parameter in `getNotificationLink` method? 
I will take a look at this too and try to help you as soon as possible

2022-07-25 21:22 UTC, MarinhoFeliphe commented
Hi @kristofloneck,

I closed this pull request, feel free to reopen when you can make the mentioned changes.

Thank you,
Feliphe

2022-07-25 21:22 UTC, closed without merging

2022-07-27 09:55 UTC, kristofloneck commented
> Hi @kristofloneck sorry for delay Could you check if it's possible fix this bug changing the `serviceContext` passed as parameter in `getNotificationLink` method? I will take a look at this too and try to help you as soon as possible


Hi @seltong 
Sorry for not answering, I was quite bussy.
It is totally possible to change the layout of original request's theme display's. The main problem is we technicly lying about what is the current layout. So we need to revert request layout to the original one in the end of the `getNotificationLink`.
This was my little magic which I mentioned in the PTR.